encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>",views.entry_page, name="title"),
    path("wiki/", views.get_search_query, name="search_query"),
    path("new", views.new_entry_page, name="new_entry"),
    path("wiki/edit/<str:title>", views.edit_entry, name="edit_entry"),
    path("random", views.random_entry, name="random_entry"),
]   

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render,redirect
from . import util,form
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
import random 

from markdown2 import Markdown

def index(request):
    """
    Lists all the entries available in the entries by using list_entries from utils.py
    """

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": form.NewSearchForm()
    })

def entry_page(request,title):
    """
    Renders a page for the entry present in the entries and if does not exist then renders error page
    """
    # Get the entry 
    entries = util.get_entry(title)
    
    # Converts entries to HTML entities
    markdowner = Markdown()
    entries_html = markdowner.convert(entries)
    
    # display entry page if entry exists
    if entries:
        return render(request, "encyclopedia/entry_page.html",{
            "title": title.capitalize(),
            "entries": entries_html,
            "form": form.NewSearchForm()   
        })
    # display error page if entry does not exist
    else: 
        return render(request, "encyclopedia/error.html",{
            "title": title,
            "form": form.NewSearchForm()
        })

def get_search_query(request):
    """
    Get the search query and return the entry page if exists else search the matching entries and display the results
    """
    if request.method == "POST":
        search_form = form.NewSearchForm(request.POST)

        if search_form.is_valid():
            title = search_form.cleaned_data["title"].lower()
            entries = util.list_entries()
            entries_lower = [entry.lower() for entry in entries]

            # when entry exists return entry page
            if title in entries_lower:
                return entry_page(request, title)
                
            else:
                # shows the matching entries
                matching_entries = []
                for entry in entries:
                    if title in entry.lower():
                        matching_entries.append(entry)

                # return all the matching entries if found
                if len(matching_entries) :
                    return render(request, "encyclopedia/title_search_result.html",{
                        "matching_entries": matching_entries,
                        "form": form.NewSearchForm()
                        })
                # else return the error page
                else:  
                    return entry_page(request, title)
                
    return render(request, "encyclopedia/title_search_result.html",{
        "form": form.NewSearchForm()
        })
    

def new_entry_page(request):
    """Lets users to create a new entry"""
    if request.method == "POST":
        new_entry_page = form.NewEntryForm(request.POST)
        # Validate form if title already exists then display error and return form
        if new_entry_page.is_valid():
            title = new_entry_page.cleaned_data['new_title']
            content = new_entry_page.cleaned_data['content']
            all_present_entries = util.list_entries()

            if title.lower() in all_present_entries:
                return render(request, "encyclopedia/new_entry_page.html",{
                        "new_entry_form": new_entry_page,
                        "form": form.NewSearchForm(),
                        "error": True,
                        "title": title,
                                    })
            # if entry does not exits then save
            else: 
                util.save_entry(title=title,content=content)
                return redirect(reverse("wiki:title", args = [title]))


    return render(request, "encyclopedia/new_entry_page.html",{
        "new_entry_form" : form.NewEntryForm(),
        "form": form.NewSearchForm(),
        "error": False,
    })


def edit_entry(request,title):
    """
    Let users edit the entry
    """
    # if entry is edited then save  
    if request.method == "POST":
        edited_entry = form.EditEntryForm(request.POST)
        if edited_entry.is_valid():
            title = edited_entry.cleaned_data['title']
            content = edited_entry.cleaned_data["content"]
            
            util.save_entry(title=title,content=content)
            return redirect(reverse("wiki:title", args = [title]))
        
    # else load content into form to edit and render it
    content = util.get_entry(title)
    edit_entry_form = form.EditEntryForm(initial={'title': title, 'content':content})

    return render(request, "encyclopedia/edit_entry_page.html",{
                "edit_entry_form" : edit_entry_form,
                "form": form.NewSearchForm(),
                "title": title,
            })

def random_entry(request):
    """Takes user to a random encyclopedia entry page"""

    # Takes all the available titles and chose randomly and returns
    titles = util.list_entries()
    title = random.choice(titles)
    
    return redirect(reverse("wiki:title", args = [title]))
    

encyclopedia/templates/encyclopedia/edit_entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit entry page
{% endblock %}

{% block body %}
    <h1> {{ title }} </h1>
    
    <form action="{% url 'wiki:edit_entry' title %}"  method="POST">  
        {% csrf_token %}
        {{ edit_entry_form.as_p }}
        <br>
        <input class="btn btn-primary" type="submit" value="Save"> </input>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}


{% block body %}

    <a class="btn btn-primary right-corner-button" href="{% url 'wiki:edit_entry' title %}"{{ title }}>Edit this page</a>
    <div>{{entries|safe}} </div>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block body %}

<p> No page found for <b>"{{ title }}"</b></p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:title' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" type="text/css" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3 ">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search_query' %}" method="post">
                    {% csrf_token %}
                    {{form}}
                </form>

                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9 ">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_entry_page.html
{% extends "encyclopedia/layout.html" %}

{% load static %}
{% block title %}
    New Entry
    
    
{% endblock %}
{% block nav %}
    

{% endblock %}
{% block body %}
    {% if  error   %}
    <div class="alert alert-danger" role="alert">
        Title '{{title}}' already exists
      </div>
    {% endif %}

    <div id = "head"> 
        <h4> New entry page </h4>
    </div>
<br> 
    <form action="{% url 'wiki:new_entry' %}"  method="POST">   
        {% csrf_token %}
        {{ new_entry_form.as_p }}
        <br>
        <input class="btn btn-primary" type="submit" value="submit"> </input>
    </form>
 
{% endblock %}

encyclopedia/templates/encyclopedia/title_search_result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>  
    <ul>
        {% for entry in matching_entries %}
            <li><a href="{% url 'wiki:title' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}